---
services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: tickers-app
    env_file:
      - ./.env.example
    environment:
      - APP_HOST=0.0.0.0
      - GIN_MODE=release
      - POSTGRES_HOST=db
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: postgres:14-alpine
    # volumes:
    #   - postgres_data:/var/lib/postgresql/data
    tmpfs:
      - /var/lib/postgresql/data
    env_file:
      - ./.env.example

# volumes:
#   postgres_data:
